// ============================================================
// Astro Camp — Mission Game Data
// Maps all 76 NASA missions (from nasa_missions_catalog.csv)
// to game types + tuned parameters
// ============================================================

export type GameType =
  | 'launch'        // Rocket ascent — Mercury, Gemini, Shuttle
  | 'docking'       // Orbital docking — Gemini rendezvous, Apollo CSM, ISS assembly
  | 'lunar_landing' // Lunar lander — Apollo, Artemis
  | 'rover'         // Surface rover — Viking, Mars rovers
  | 'telescope'     // Telescope calibration — Hubble, JWST, Chandra, Kepler
  | 'deep_space';   // Gravity slingshot — Voyager, Cassini, New Horizons

export interface MissionGameConfig {
  id: string;
  missionName: string;
  programName: string;
  year: string;
  gameType: GameType;
  difficulty: 1 | 2 | 3 | 4 | 5; // 1=easiest, 5=hardest
  briefing: string;
  objective: string;
  funFact: string;
  // Game-type-specific parameters
  params: LaunchParams | DockingParams | LunarLandingParams | RoverParams | TelescopeParams | DeepSpaceParams;
}

// ──────────────────────────────────────────────
// Parameter Interfaces per Game Type
// ──────────────────────────────────────────────

export interface LaunchParams {
  targetAltitudeKm: number;
  targetVelocityKms: number;
  fuelCapacity: number;
  windEnabled: boolean;
  hasStageSeparation: boolean;
  trajectoryWindowDeg: number; // allowed deviation degrees from guidance
  timeWindowSec: number;
}

export interface DockingParams {
  approachDistanceM: number;
  maxApproachSpeedMs: number;
  portDiameterPx: number; // target circle size — smaller = harder
  thrusterStrength: number;
  damping: number; // 0–1, how quickly velocity bleeds
  hasRollAxis: boolean;
  timeLimitSec: number;
}

export interface LunarLandingParams {
  gravity: number; // m/s² — Moon 1.62, Mars 3.72
  fuelCapacity: number;
  targetZoneWidthPx: number; // narrower = harder
  windDrift: number; // lateral force
  hasTerrainHazards: boolean;
  timeLimitSec: number;
  altitudeStartM: number;
}

export interface RoverParams {
  gridCols: number;
  gridRows: number;
  craterDensity: number; // 0–1
  numWaypoints: number;
  batteryCapacity: number;
  sandstormProbability: number; // 0–1
  timeLimitSec: number;
}

export interface TelescopeParams {
  shimmerAmplitude: number; // 0–1 atmospheric distortion
  targetSizePx: number;
  numTargets: number;
  lockTimeSec: number; // how long to hold lock per target
  hasDrift: boolean;
  timeLimitSec: number;
}

export interface DeepSpaceParams {
  numPlanets: number;
  requiredSwingbys: number;
  fuelBudget: number;
  targetOrbitalRadius: number;
  gravityStrength: number;
  timeLimitSec: number;
}

// ──────────────────────────────────────────────
// All 76 Mission Configurations
// ──────────────────────────────────────────────

export const MISSION_GAME_DATA: MissionGameConfig[] = [
  // ═══════════════════════════════
  // PROJECT MERCURY (M001–M006)
  // ═══════════════════════════════
  {
    id: 'NASA-M001',
    missionName: 'Mercury-Redstone 3 (Freedom 7)',
    programName: 'Project Mercury',
    year: '1961',
    gameType: 'launch',
    difficulty: 1,
    briefing: 'You are Alan Shepard — the first American in space. Your Redstone rocket must follow a precise suborbital arc to reach 116 miles altitude.',
    objective: 'Throttle and steer the Redstone rocket to hit the target altitude within the guidance window.',
    funFact: 'Shepard had just 15 minutes of weightlessness — but he tested every manual control system.',
    params: {
      targetAltitudeKm: 187,
      targetVelocityKms: 2.3,
      fuelCapacity: 100,
      windEnabled: false,
      hasStageSeparation: false,
      trajectoryWindowDeg: 12,
      timeWindowSec: 45,
    } as LaunchParams,
  },
  {
    id: 'NASA-M002',
    missionName: 'Mercury-Redstone 4 (Liberty Bell 7)',
    programName: 'Project Mercury',
    year: '1961',
    gameType: 'launch',
    difficulty: 1,
    briefing: "Gus Grissom's suborbital flight. Same arc as Freedom 7 — but the explosive hatch fired prematurely after splashdown. Keep your cool.",
    objective: 'Nail the ascent trajectory then manually trigger reentry at the correct apex.',
    funFact: "Liberty Bell 7 sank to the ocean floor in 1961. It was recovered from 3 miles down in 1999.",
    params: {
      targetAltitudeKm: 190,
      targetVelocityKms: 2.3,
      fuelCapacity: 100,
      windEnabled: false,
      hasStageSeparation: false,
      trajectoryWindowDeg: 10,
      timeWindowSec: 45,
    } as LaunchParams,
  },
  {
    id: 'NASA-M003',
    missionName: 'Mercury-Atlas 6 (Friendship 7)',
    programName: 'Project Mercury',
    year: '1962',
    gameType: 'launch',
    difficulty: 2,
    briefing: "John Glenn — America's first orbital flight. The Atlas rocket must reach orbital velocity. Ground controllers suspected your heat shield was loose — you had to reenter manually.",
    objective: 'Achieve 3 full Earth orbits, then manually override autopilot for retrofire.',
    funFact: "Glenn saw sunsets and sunrises every 90 minutes. He was also 40 years old — NASA's oldest Mercury astronaut.",
    params: {
      targetAltitudeKm: 265,
      targetVelocityKms: 7.8,
      fuelCapacity: 100,
      windEnabled: true,
      hasStageSeparation: true,
      trajectoryWindowDeg: 8,
      timeWindowSec: 60,
    } as LaunchParams,
  },
  {
    id: 'NASA-M004',
    missionName: 'Mercury-Atlas 7 (Aurora 7)',
    programName: 'Project Mercury',
    year: '1962',
    gameType: 'launch',
    difficulty: 2,
    briefing: "Scott Carpenter burns too much thruster fuel on horizon tracking experiments. Manage fuel carefully — you need enough for retro-rocket burn.",
    objective: 'Complete orbital science maneuvers while keeping fuel above 15% for retrofire.',
    funFact: "Carpenter overshot his landing zone by 400 km due to retrofire angle error — and survived!",
    params: {
      targetAltitudeKm: 272,
      targetVelocityKms: 7.8,
      fuelCapacity: 80,
      windEnabled: true,
      hasStageSeparation: true,
      trajectoryWindowDeg: 8,
      timeWindowSec: 60,
    } as LaunchParams,
  },
  {
    id: 'NASA-M005',
    missionName: 'Mercury-Atlas 8 (Sigma 7)',
    programName: 'Project Mercury',
    year: '1962',
    gameType: 'launch',
    difficulty: 2,
    briefing: "Walter Schirra's engineering evaluation — the mission goal is fuel CONSERVATION. Use minimum thruster pulses.",
    objective: 'Complete 6 orbits using less than 20% of your reaction control fuel.',
    funFact: "Schirra was so efficient he landed with 78% of his fuel remaining — a Mercury record.",
    params: {
      targetAltitudeKm: 285,
      targetVelocityKms: 7.8,
      fuelCapacity: 60,
      windEnabled: false,
      hasStageSeparation: true,
      trajectoryWindowDeg: 6,
      timeWindowSec: 75,
    } as LaunchParams,
  },
  {
    id: 'NASA-M006',
    missionName: 'Mercury-Atlas 9 (Faith 7)',
    programName: 'Project Mercury',
    year: '1963',
    gameType: 'launch',
    difficulty: 3,
    briefing: "Gordon Cooper — 22 orbits over 34 hours. Your electrical system fails at orbit 20. Manually align for reentry using only a periscope and your wristwatch.",
    objective: 'Complete the long-duration flight, then manually execute reentry after electrical failure.',
    funFact: "Cooper manually computed his own reentry trajectory using a stopwatch. He splashed down just 6 km from the recovery ship.",
    params: {
      targetAltitudeKm: 267,
      targetVelocityKms: 7.8,
      fuelCapacity: 100,
      windEnabled: true,
      hasStageSeparation: true,
      trajectoryWindowDeg: 5,
      timeWindowSec: 90,
    } as LaunchParams,
  },

  // ═══════════════════════════════
  // PROJECT GEMINI (M007–M017)
  // ═══════════════════════════════
  {
    id: 'NASA-M007',
    missionName: 'Gemini 1 & 2',
    programName: 'Project Gemini',
    year: '1964–1965',
    gameType: 'launch',
    difficulty: 1,
    briefing: 'Uncrewed Titan II tests. Verify the structural integrity of the rocket and heat shield before humans fly.',
    objective: 'Execute automated launch sequence and confirm heat shield separation.',
    funFact: 'Gemini 1 remained attached to its Titan II booster to test structural loads — it was never meant to reenter.',
    params: {
      targetAltitudeKm: 320,
      targetVelocityKms: 7.9,
      fuelCapacity: 100,
      windEnabled: false,
      hasStageSeparation: true,
      trajectoryWindowDeg: 15,
      timeWindowSec: 40,
    } as LaunchParams,
  },
  {
    id: 'NASA-M008',
    missionName: 'Gemini 3',
    programName: 'Project Gemini',
    year: '1965',
    gameType: 'docking',
    difficulty: 1,
    briefing: "Gus Grissom and John Young — first crewed Gemini. Test the Orbital Attitude and Maneuvering System (OAMS). Change your orbital plane for the first time in history.",
    objective: 'Fire OAMS thrusters to match a new orbital plane within ±2 km.',
    funFact: "John Young secretly smuggled a corned beef sandwich aboard. It got crumbs in the cockpit — NASA was not amused.",
    params: {
      approachDistanceM: 5000,
      maxApproachSpeedMs: 8,
      portDiameterPx: 80,
      thrusterStrength: 1.2,
      damping: 0.92,
      hasRollAxis: false,
      timeLimitSec: 90,
    } as DockingParams,
  },
  {
    id: 'NASA-M009',
    missionName: 'Gemini 4',
    programName: 'Project Gemini',
    year: '1965',
    gameType: 'docking',
    difficulty: 2,
    briefing: "Ed White performs America's first spacewalk. Control the Hand-Held Maneuvering Unit (HHMU) — a small nitrogen-gas gun — to stay tethered and within range.",
    objective: "Maneuver the EVA astronaut within 10m of the capsule using the HHMU thruster gun.",
    funFact: "White enjoyed his spacewalk so much he said 'I'm coming back in... it's the saddest moment of my life.' Mission Control had to order him back in.",
    params: {
      approachDistanceM: 300,
      maxApproachSpeedMs: 2,
      portDiameterPx: 120,
      thrusterStrength: 0.4,
      damping: 0.85,
      hasRollAxis: false,
      timeLimitSec: 120,
    } as DockingParams,
  },
  {
    id: 'NASA-M010',
    missionName: 'Gemini 5',
    programName: 'Project Gemini',
    year: '1965',
    gameType: 'launch',
    difficulty: 2,
    briefing: "8-day endurance mission. Your fuel cells are experimental — power output degrades over time. Monitor fuel cell pressure and conserve power.",
    objective: 'Complete 8-day orbit while keeping fuel cell pressure above minimum threshold.',
    funFact: 'Gemini 5 flew 128 orbits — proving humans could survive the two weeks needed to reach the Moon and back.',
    params: {
      targetAltitudeKm: 348,
      targetVelocityKms: 7.9,
      fuelCapacity: 90,
      windEnabled: false,
      hasStageSeparation: true,
      trajectoryWindowDeg: 8,
      timeWindowSec: 70,
    } as LaunchParams,
  },
  {
    id: 'NASA-M011',
    missionName: 'Gemini 7',
    programName: 'Project Gemini',
    year: '1965',
    gameType: 'docking',
    difficulty: 2,
    briefing: "Frank Borman and Jim Lovell endure 14 days in orbit — the record at the time. Your spacecraft becomes the rendezvous target for Gemini 6A.",
    objective: 'Maintain station-keeping orbit while Gemini 6A approaches.',
    funFact: "The cabin was so small Borman and Lovell couldn't both extend their legs at the same time for 14 days.",
    params: {
      approachDistanceM: 2000,
      maxApproachSpeedMs: 3,
      portDiameterPx: 100,
      thrusterStrength: 0.8,
      damping: 0.94,
      hasRollAxis: false,
      timeLimitSec: 100,
    } as DockingParams,
  },
  {
    id: 'NASA-M012',
    missionName: 'Gemini 6A',
    programName: 'Project Gemini',
    year: '1965',
    gameType: 'docking',
    difficulty: 3,
    briefing: "Schirra and Stafford — the first space rendezvous in history. Close within 1 foot of Gemini 7 using only radar guidance. No docking hardware — pure precision flying.",
    objective: 'Close to within 30cm of Gemini 7 and hold station for 5 seconds.',
    funFact: 'The two crews were so close they could see each other through the windows. Schirra held up a "Beat Army" sign.',
    params: {
      approachDistanceM: 1200,
      maxApproachSpeedMs: 2,
      portDiameterPx: 40,
      thrusterStrength: 1.0,
      damping: 0.96,
      hasRollAxis: false,
      timeLimitSec: 110,
    } as DockingParams,
  },
  {
    id: 'NASA-M013',
    missionName: 'Gemini 8',
    programName: 'Project Gemini',
    year: '1966',
    gameType: 'docking',
    difficulty: 4,
    briefing: "Neil Armstrong and Dave Scott complete the first docking in space with Agena. Then a stuck thruster sends you into a 1-revolution-per-second spin. Emergency undock — or you'll black out.",
    objective: 'Dock with the Agena, then immediately undock and stabilize when thruster 8 sticks.',
    funFact: "Armstrong was spinning so fast (1 rev/sec) he was close to losing consciousness when he managed to stabilize using reentry thrusters.",
    params: {
      approachDistanceM: 800,
      maxApproachSpeedMs: 3,
      portDiameterPx: 55,
      thrusterStrength: 1.5,
      damping: 0.90,
      hasRollAxis: true,
      timeLimitSec: 95,
    } as DockingParams,
  },
  {
    id: 'NASA-M014',
    missionName: 'Gemini 9A',
    programName: 'Project Gemini',
    year: '1966',
    gameType: 'docking',
    difficulty: 3,
    briefing: "Tom Stafford and Gene Cernan. The docking adapter shroud failed to jettison — it looks like an 'angry alligator'. Rendezvous anyway and test EVA maneuvering.",
    objective: 'Rendezvous within 10m of the target and complete the EVA maneuver sequence.',
    funFact: "Cernan's spacewalk was so exhausting his helmet fogged up completely — he could barely see.",
    params: {
      approachDistanceM: 1500,
      maxApproachSpeedMs: 4,
      portDiameterPx: 60,
      thrusterStrength: 1.1,
      damping: 0.92,
      hasRollAxis: false,
      timeLimitSec: 100,
    } as DockingParams,
  },
  {
    id: 'NASA-M015',
    missionName: 'Gemini 10',
    programName: 'Project Gemini',
    year: '1966',
    gameType: 'docking',
    difficulty: 3,
    briefing: "John Young and Michael Collins perform a dual rendezvous. Use the Agena's engine to boost your orbit — then rendezvous with a SECOND passive Agena from Gemini 8.",
    objective: 'Dock with Agena-10, use its engine to reach Agena-8, then retrieve the micrometeorite collector.',
    funFact: 'Collins retrieved hardware from another spacecraft — the first time anyone had done this in EVA.',
    params: {
      approachDistanceM: 2000,
      maxApproachSpeedMs: 5,
      portDiameterPx: 65,
      thrusterStrength: 1.3,
      damping: 0.91,
      hasRollAxis: false,
      timeLimitSec: 105,
    } as DockingParams,
  },
  {
    id: 'NASA-M016',
    missionName: 'Gemini 11',
    programName: 'Project Gemini',
    year: '1966',
    gameType: 'docking',
    difficulty: 4,
    briefing: "Pete Conrad and Dick Gordon — first orbit direct ascent rendezvous (no waiting). Then tether the Agena and create artificial gravity by rotating the pair.",
    objective: 'Dock on the FIRST orbit, tether to Agena, and achieve stable artificial gravity rotation.',
    funFact: 'Gemini 11 reached 1,374 km — the highest Earth orbit ever by humans (outside of lunar flights). You could see the entire African continent.',
    params: {
      approachDistanceM: 400,
      maxApproachSpeedMs: 2,
      portDiameterPx: 50,
      thrusterStrength: 1.4,
      damping: 0.93,
      hasRollAxis: true,
      timeLimitSec: 80,
    } as DockingParams,
  },
  {
    id: 'NASA-M017',
    missionName: 'Gemini 12',
    programName: 'Project Gemini',
    year: '1966',
    gameType: 'docking',
    difficulty: 3,
    briefing: "Buzz Aldrin masters EVA with underwater training. Use foot restraints and handholds to complete 5.5 hours of spacewalks without exhaustion.",
    objective: 'Complete all 3 EVA sessions maintaining body stability with foot restraints.',
    funFact: 'Aldrin proved EVA could be mastered through underwater training — a technique still used today.',
    params: {
      approachDistanceM: 900,
      maxApproachSpeedMs: 3,
      portDiameterPx: 70,
      thrusterStrength: 1.0,
      damping: 0.94,
      hasRollAxis: false,
      timeLimitSec: 105,
    } as DockingParams,
  },

  // ═══════════════════════════════
  // APOLLO PROGRAM (M018–M030)
  // ═══════════════════════════════
  {
    id: 'NASA-M018',
    missionName: 'Apollo 1',
    programName: 'Apollo Program',
    year: '1967',
    gameType: 'launch',
    difficulty: 2,
    briefing: 'A memorial mission. Learn what went wrong in the Apollo 1 cabin fire — 100% oxygen at high pressure. Your task: identify the design flaws and correct them before the spacecraft is cleared to fly.',
    objective: 'Identify all 5 fire hazards in the cabin schematic before time runs out.',
    funFact: "The Apollo 1 fire led to a complete redesign of the hatch (opens outward in <3 seconds) and replacement of 1,407 wiring failures found in the spacecraft.",
    params: {
      targetAltitudeKm: 0,
      targetVelocityKms: 0,
      fuelCapacity: 100,
      windEnabled: false,
      hasStageSeparation: false,
      trajectoryWindowDeg: 20,
      timeWindowSec: 60,
    } as LaunchParams,
  },
  {
    id: 'NASA-M019',
    missionName: 'Apollo 4, 5, 6',
    programName: 'Apollo Program',
    year: '1967–1968',
    gameType: 'launch',
    difficulty: 2,
    briefing: "Saturn V qualification — the most powerful rocket ever built. 7.5 million pounds of thrust at liftoff. Fly the uncrewed test missions to validate staging and reentry.",
    objective: 'Execute 3-stage Saturn V staging and heat shield qualification reentry.',
    funFact: "Saturn V was so powerful its launch was detected on seismographs 100 miles away.",
    params: {
      targetAltitudeKm: 18000,
      targetVelocityKms: 10.4,
      fuelCapacity: 100,
      windEnabled: true,
      hasStageSeparation: true,
      trajectoryWindowDeg: 6,
      timeWindowSec: 80,
    } as LaunchParams,
  },
  {
    id: 'NASA-M020',
    missionName: 'Apollo 7',
    programName: 'Apollo Program',
    year: '1968',
    gameType: 'docking',
    difficulty: 2,
    briefing: "First crewed Apollo orbital test. Test the Service Propulsion System (SPS) engine with 8 firings. Rendezvous with the spent Saturn S-IVB stage.",
    objective: 'Fire SPS 8 times at precise intervals and rendezvous with the S-IVB.',
    funFact: 'Apollo 7 also aired the first live TV broadcast from an American spacecraft. Commander Wally Schirra had a bad cold and complained about everything.',
    params: {
      approachDistanceM: 3000,
      maxApproachSpeedMs: 6,
      portDiameterPx: 90,
      thrusterStrength: 1.2,
      damping: 0.92,
      hasRollAxis: false,
      timeLimitSec: 100,
    } as DockingParams,
  },
  {
    id: 'NASA-M021',
    missionName: 'Apollo 8',
    programName: 'Apollo Program',
    year: '1968',
    gameType: 'deep_space',
    difficulty: 3,
    briefing: "Borman, Lovell, and Anders — humanity first leaves Earth's gravity well. Execute Trans-Lunar Injection (TLI), then brake into lunar orbit. If the LOI burn fails, you will fly past the Moon forever.",
    objective: 'Execute TLI burn correctly, enter lunar orbit, then fire TEI to return home.',
    funFact: "Apollo 8 launched on December 21, 1968 — the crew read Genesis from lunar orbit on Christmas Eve. 1 billion people listened.",
    params: {
      numPlanets: 1,
      requiredSwingbys: 0,
      fuelBudget: 100,
      targetOrbitalRadius: 1800,
      gravityStrength: 1.62,
      timeLimitSec: 120,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M022',
    missionName: 'Apollo 9',
    programName: 'Apollo Program',
    year: '1969',
    gameType: 'docking',
    difficulty: 3,
    briefing: "First crewed test of the Lunar Module in Earth orbit. Extract the LM from the Saturn stack, separate, fire descent engine, then rendezvous and redock — as if you're at the Moon.",
    objective: 'Extract LM from Saturn, separate 15km, fire descent engine, rendezvous, and dock.',
    funFact: "The LM was so fragile it couldn't survive Earth's atmosphere — it was built only for space.",
    params: {
      approachDistanceM: 15000,
      maxApproachSpeedMs: 8,
      portDiameterPx: 60,
      thrusterStrength: 1.3,
      damping: 0.91,
      hasRollAxis: true,
      timeLimitSec: 120,
    } as DockingParams,
  },
  {
    id: 'NASA-M023',
    missionName: 'Apollo 10',
    programName: 'Apollo Program',
    year: '1969',
    gameType: 'lunar_landing',
    difficulty: 3,
    briefing: "Stafford and Cernan descend to within 8.4 nautical miles of the lunar surface — but DO NOT land. This is the dress rehearsal. Fire the ascent stage at the correct altitude.",
    objective: 'Descend to 15km altitude, hold, then fire ascent stage to rendezvous with Collins.',
    funFact: "The ascent stage accidentally switched to 'auto' mode and started gyrating wildly — Cernan yelled 'Son of a bitch!' — caught on the transcript.",
    params: {
      gravity: 1.62,
      fuelCapacity: 100,
      targetZoneWidthPx: 0, // no landing — just altitude hold
      windDrift: 0,
      hasTerrainHazards: false,
      timeLimitSec: 120,
      altitudeStartM: 110000,
    } as LunarLandingParams,
  },
  {
    id: 'NASA-M024',
    missionName: 'Apollo 11',
    programName: 'Apollo Program',
    year: '1969',
    gameType: 'lunar_landing',
    difficulty: 4,
    briefing: "The most watched event in human history. Armstrong and Aldrin descend to the Sea of Tranquility. The computer alarm fires — 1202! But Gene Kranz says GO. A boulder field appears. You have 30 seconds of fuel.",
    objective: 'Land the Eagle in the target zone while avoiding the boulder field. 30 seconds of fuel left.',
    funFact: "Armstrong had 17 seconds of fuel left when the Eagle landed. The 1202 alarm meant the computer was overloaded — but the landing guidance was still good.",
    params: {
      gravity: 1.62,
      fuelCapacity: 30,
      targetZoneWidthPx: 90,
      windDrift: 0,
      hasTerrainHazards: true,
      timeLimitSec: 90,
      altitudeStartM: 2000,
    } as LunarLandingParams,
  },
  {
    id: 'NASA-M025',
    missionName: 'Apollo 12',
    programName: 'Apollo Program',
    year: '1969',
    gameType: 'lunar_landing',
    difficulty: 4,
    briefing: "Pete Conrad aims for a pinpoint landing 200m from Surveyor 3 — a robot that's been sitting on the Moon for 2.5 years. Lightning struck the Saturn V twice at launch.",
    objective: 'Land within 200m of the Surveyor 3 target marker. Then walk to it and retrieve its camera.',
    funFact: "Conrad landed so precisely he could see Surveyor 3 from the cockpit window. He won a bet with a NASA contractor.",
    params: {
      gravity: 1.62,
      fuelCapacity: 80,
      targetZoneWidthPx: 60,
      windDrift: 0,
      hasTerrainHazards: true,
      timeLimitSec: 100,
      altitudeStartM: 3000,
    } as LunarLandingParams,
  },
  {
    id: 'NASA-M026',
    missionName: 'Apollo 13',
    programName: 'Apollo Program',
    year: '1970',
    gameType: 'deep_space',
    difficulty: 5,
    briefing: "Houston, we've had a problem. Oxygen Tank 2 explodes 200,000 miles from Earth. The Command Module is dying. Use the Lunar Module as a lifeboat. Manual burn using the sun as your guide. Get home.",
    objective: 'Execute the PC+2 burn using LM Aquarius to get a free-return trajectory. Navigate home with limited power.',
    funFact: "The crew had 15 minutes of power left when they splashed down. Engineers at Mission Control invented a CO₂ scrubber using only materials on the ship.",
    params: {
      numPlanets: 1,
      requiredSwingbys: 1,
      fuelBudget: 40,
      targetOrbitalRadius: 6371,
      gravityStrength: 1.62,
      timeLimitSec: 150,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M027',
    missionName: 'Apollo 14',
    programName: 'Apollo Program',
    year: '1971',
    gameType: 'rover',
    difficulty: 3,
    briefing: "Alan Shepard and Ed Mitchell at Fra Mauro. Deploy the MET handcart and traverse across rugged highland terrain to the rim of Cone Crater — collecting geological samples.",
    objective: 'Navigate the MET handcart to Cone Crater rim and collect 5 geological samples.',
    funFact: "Shepard hit two golf balls on the Moon with a makeshift club. They went 'miles and miles and miles' — in lunar gravity, maybe 400m.",
    params: {
      gridCols: 12,
      gridRows: 12,
      craterDensity: 0.25,
      numWaypoints: 5,
      batteryCapacity: 100,
      sandstormProbability: 0,
      timeLimitSec: 120,
    } as RoverParams,
  },
  {
    id: 'NASA-M028',
    missionName: 'Apollo 15',
    programName: 'Apollo Program',
    year: '1971',
    gameType: 'rover',
    difficulty: 3,
    briefing: "First Lunar Roving Vehicle — an electric dune buggy on the Moon! Scott and Irwin at Hadley Rille. The LRV can go 13 km/h and has its own navigation display.",
    objective: 'Drive the LRV to Hadley Rille rim, collect deep-core drill samples, and return before battery depletes.',
    funFact: "Apollo 15 found the 'Genesis Rock' — a piece of the Moon's original crust, 4 billion years old.",
    params: {
      gridCols: 16,
      gridRows: 16,
      craterDensity: 0.3,
      numWaypoints: 6,
      batteryCapacity: 100,
      sandstormProbability: 0,
      timeLimitSec: 130,
    } as RoverParams,
  },
  {
    id: 'NASA-M029',
    missionName: 'Apollo 16',
    programName: 'Apollo Program',
    year: '1972',
    gameType: 'rover',
    difficulty: 3,
    briefing: "Young and Duke at Descartes crater — highland terrain, rougher than any previous site. The LRV must cover 27 km across ridgelines to collect 95 kg of samples.",
    objective: 'Drive the LRV across 4 waypoints collecting rock samples. Avoid large craters.',
    funFact: "John Young jumped so high saluting the flag that it kicked up a huge dust cloud and nearly knocked Lunar Module over.",
    params: {
      gridCols: 14,
      gridRows: 14,
      craterDensity: 0.35,
      numWaypoints: 4,
      batteryCapacity: 95,
      sandstormProbability: 0,
      timeLimitSec: 120,
    } as RoverParams,
  },
  {
    id: 'NASA-M030',
    missionName: 'Apollo 17',
    programName: 'Apollo Program',
    year: '1972',
    gameType: 'rover',
    difficulty: 4,
    briefing: "The last lunar landing — and the most scientific. Scientist-astronaut Harrison Schmitt drives the LRV to the orange soil discovery at Shorty Crater. 22 total EVA hours.",
    objective: 'Complete 3 LRV traverses, find the orange glass deposit at Shorty Crater, and repair the broken fender.',
    funFact: "Schmitt discovered orange volcanic glass — proof of ancient volcanic eruptions. The crew sang 'I Was Strolling on the Moon' over the radio.",
    params: {
      gridCols: 18,
      gridRows: 14,
      craterDensity: 0.3,
      numWaypoints: 7,
      batteryCapacity: 100,
      sandstormProbability: 0,
      timeLimitSec: 140,
    } as RoverParams,
  },

  // ═══════════════════════════════
  // SKYLAB & APOLLO-SOYUZ (M031–M032)
  // ═══════════════════════════════
  {
    id: 'NASA-M031',
    missionName: 'Skylab 1, 2, 3, 4',
    programName: 'Skylab Program',
    year: '1973–1974',
    gameType: 'docking',
    difficulty: 3,
    briefing: "Skylab launched damaged — a solar array is stuck and the thermal shield ripped off. EVA to deploy an emergency parasol and free the jammed solar panel.",
    objective: 'Dock with Skylab, EVA to deploy the parasol, and free the stuck solar panel.',
    funFact: "The repair saved Skylab and let 3 crews live aboard for up to 84 days. Without the fix, the station would have overheated and failed.",
    params: {
      approachDistanceM: 5000,
      maxApproachSpeedMs: 5,
      portDiameterPx: 75,
      thrusterStrength: 1.1,
      damping: 0.92,
      hasRollAxis: false,
      timeLimitSec: 110,
    } as DockingParams,
  },
  {
    id: 'NASA-M032',
    missionName: 'Apollo-Soyuz Test Project',
    programName: 'Apollo-Soyuz',
    year: '1975',
    gameType: 'docking',
    difficulty: 3,
    briefing: "Cold War space détente. An American Apollo and a Soviet Soyuz dock in orbit. Both sides use a shared Universal Docking Module. Precision approach from the US side.",
    objective: 'Dock the Apollo capsule with the Soviet Soyuz using the Universal Docking Adapter.',
    funFact: "After docking, the crews shook hands in orbit and shared meals. Alexei Leonov gave Tom Stafford Soviet vodka (actually borscht in labeled tubes).",
    params: {
      approachDistanceM: 2000,
      maxApproachSpeedMs: 4,
      portDiameterPx: 70,
      thrusterStrength: 1.0,
      damping: 0.93,
      hasRollAxis: false,
      timeLimitSec: 100,
    } as DockingParams,
  },

  // ═══════════════════════════════
  // SPACE SHUTTLE (M033–M044)
  // ═══════════════════════════════
  {
    id: 'NASA-M033',
    missionName: 'STS-1 (Columbia)',
    programName: 'Space Shuttle Program',
    year: '1981',
    gameType: 'launch',
    difficulty: 3,
    briefing: "Young and Crippen fly the first Space Shuttle. Solid boosters separate at 45km. The Shuttle glides back — no engine, no second chance — to a lakebed runway at Edwards.",
    objective: 'Separate SRBs at the right moment, then guide Columbia in an unpowered glide to the runway.',
    funFact: "STS-1 was the first American crewed spacecraft NOT to fly uncrewed first. The crew was the test crew.",
    params: {
      targetAltitudeKm: 250,
      targetVelocityKms: 7.8,
      fuelCapacity: 100,
      windEnabled: true,
      hasStageSeparation: true,
      trajectoryWindowDeg: 5,
      timeWindowSec: 80,
    } as LaunchParams,
  },
  {
    id: 'NASA-M034',
    missionName: 'STS-6 (Challenger)',
    programName: 'Space Shuttle Program',
    year: '1983',
    gameType: 'docking',
    difficulty: 2,
    briefing: "Maiden flight of Challenger. Deploy the TDRS-1 satellite and perform the first Shuttle spacewalk to qualify the new EMU suit.",
    objective: 'Deploy TDRS-1 from the cargo bay using the robot arm, then complete the EVA checkouts.',
    funFact: 'STS-6 showed the Shuttle could carry heavy satellites AND perform spacewalks — the full vision of a reusable space truck.',
    params: {
      approachDistanceM: 200,
      maxApproachSpeedMs: 1,
      portDiameterPx: 100,
      thrusterStrength: 0.8,
      damping: 0.95,
      hasRollAxis: false,
      timeLimitSec: 90,
    } as DockingParams,
  },
  {
    id: 'NASA-M035',
    missionName: 'STS-7 (Challenger)',
    programName: 'Space Shuttle Program',
    year: '1983',
    gameType: 'docking',
    difficulty: 2,
    briefing: "Sally Ride becomes the first American woman in space. Operate the Shuttle Remote Manipulator System (RMS) robot arm to deploy and then retrieve the SPAS-01 satellite.",
    objective: 'Deploy SPAS-01 with the robot arm, maneuver Challenger away, then grapple and retrieve it.',
    funFact: "Sally Ride was selected from 8,000 applicants. A senator asked NASA if she would be 'off her cycle' during the mission — she ignored him.",
    params: {
      approachDistanceM: 300,
      maxApproachSpeedMs: 1.5,
      portDiameterPx: 90,
      thrusterStrength: 0.9,
      damping: 0.94,
      hasRollAxis: false,
      timeLimitSec: 100,
    } as DockingParams,
  },
  {
    id: 'NASA-M036',
    missionName: 'STS-41C (Challenger)',
    programName: 'Space Shuttle Program',
    year: '1984',
    gameType: 'docking',
    difficulty: 4,
    briefing: "First in-orbit satellite repair. George Nelson launches from the Shuttle in the Manned Maneuvering Unit (MMU) jetpack — untethered. He must capture the tumbling Solar Max satellite and wrestle it still.",
    objective: 'Fly the MMU to Solar Max, grapple the tumbling satellite, and stabilize it in the cargo bay.',
    funFact: 'Nelson tried to attach a capture tool to Solar Max — but it failed. He physically grabbed the satellite with his hands, which also failed. A robot arm finally saved the day.',
    params: {
      approachDistanceM: 500,
      maxApproachSpeedMs: 2,
      portDiameterPx: 45,
      thrusterStrength: 0.6,
      damping: 0.88,
      hasRollAxis: true,
      timeLimitSec: 110,
    } as DockingParams,
  },
  {
    id: 'NASA-M037',
    missionName: 'STS-51L (Challenger)',
    programName: 'Space Shuttle Program',
    year: '1986',
    gameType: 'launch',
    difficulty: 5,
    briefing: "A memorial mission. A cold O-ring seal fails at launch. This is an engineering failure investigation. Identify which O-ring joint failed and why launch was approved despite warnings.",
    objective: 'Review the SRB joint engineering data and correctly identify all 5 failure points before T-0.',
    funFact: "Engineer Roger Boisjoly warned NASA the night before the launch that the O-rings would fail in cold temperatures. He was overruled.",
    params: {
      targetAltitudeKm: 0,
      targetVelocityKms: 0,
      fuelCapacity: 100,
      windEnabled: false,
      hasStageSeparation: false,
      trajectoryWindowDeg: 25,
      timeWindowSec: 60,
    } as LaunchParams,
  },
  {
    id: 'NASA-M038',
    missionName: 'STS-26 (Discovery)',
    programName: 'Space Shuttle Program',
    year: '1988',
    gameType: 'launch',
    difficulty: 3,
    briefing: "Return to flight after the Challenger disaster — 32 months of redesigns. Every system has changed. The crew wears full pressure suits. Launch with the redesigned SRB field joints.",
    objective: 'Execute a clean launch sequence with the redesigned SRBs and confirm all safety systems.',
    funFact: "The STS-26 crew flew a banner showing a broken chain — restored. The whole country watched.",
    params: {
      targetAltitudeKm: 296,
      targetVelocityKms: 7.8,
      fuelCapacity: 100,
      windEnabled: true,
      hasStageSeparation: true,
      trajectoryWindowDeg: 5,
      timeWindowSec: 80,
    } as LaunchParams,
  },
  {
    id: 'NASA-M039',
    missionName: 'STS-31 (Discovery)',
    programName: 'Space Shuttle Program',
    year: '1990',
    gameType: 'docking',
    difficulty: 3,
    briefing: "Deploy the Hubble Space Telescope. The 12-meter robot arm must lift 11 tons into a 612 km orbit — the highest Shuttle ever flew. Careful: any tumble and Hubble is lost.",
    objective: 'Use the robot arm to gently lift and release Hubble into a stable deployment attitude.',
    funFact: "Only after Hubble was deployed did NASA realize its primary mirror was ground to the wrong shape — 2mm off. It needed contact lenses.",
    params: {
      approachDistanceM: 100,
      maxApproachSpeedMs: 0.5,
      portDiameterPx: 120,
      thrusterStrength: 0.7,
      damping: 0.97,
      hasRollAxis: false,
      timeLimitSec: 100,
    } as DockingParams,
  },
  {
    id: 'NASA-M040',
    missionName: 'STS-71 (Atlantis)',
    programName: 'Space Shuttle Program',
    year: '1995',
    gameType: 'docking',
    difficulty: 4,
    briefing: "First Shuttle-Mir docking. Approach the Russian station in a tight proximity corridor — jets firing could damage Mir's solar arrays. Use precision RCS pulses only.",
    objective: 'Dock with Mir\'s Kristall module using only micro-thruster pulses within 5° of the docking axis.',
    funFact: 'The Shuttle-Mir program laid the groundwork for ISS — proving US and Russian space systems could physically integrate.',
    params: {
      approachDistanceM: 2000,
      maxApproachSpeedMs: 3,
      portDiameterPx: 55,
      thrusterStrength: 0.8,
      damping: 0.95,
      hasRollAxis: true,
      timeLimitSec: 110,
    } as DockingParams,
  },
  {
    id: 'NASA-M041',
    missionName: 'STS-88 (Endeavour)',
    programName: 'Space Shuttle Program',
    year: '1998',
    gameType: 'docking',
    difficulty: 4,
    briefing: "First ISS assembly flight. Mate the US Unity node to the Russian Zarya module. 3 spacewalks connect electrical cables and antennas between two modules built on different continents.",
    objective: 'Use the robot arm to align Unity with Zarya, hard-mate the modules, then complete 3 EVAs to connect umbilicals.',
    funFact: "STS-88 created the foundation of humanity's first permanent home in space. Zarya was Russian-built but US-funded.",
    params: {
      approachDistanceM: 500,
      maxApproachSpeedMs: 2,
      portDiameterPx: 55,
      thrusterStrength: 0.9,
      damping: 0.95,
      hasRollAxis: true,
      timeLimitSec: 120,
    } as DockingParams,
  },
  {
    id: 'NASA-M042',
    missionName: 'STS-107 (Columbia)',
    programName: 'Space Shuttle Program',
    year: '2003',
    gameType: 'launch',
    difficulty: 5,
    briefing: "A memorial mission. During launch, foam from the External Tank struck Columbia's left wing. This is a heat-shield damage investigation. Identify the breach location before reentry.",
    objective: 'Trace the foam impact vector and identify the damaged RCC panel that caused the reentry failure.',
    funFact: "An engineer emailed NASA warning about the foam strike. The email was not acted on. Columbia disintegrated over Texas at 61km altitude.",
    params: {
      targetAltitudeKm: 0,
      targetVelocityKms: 0,
      fuelCapacity: 100,
      windEnabled: false,
      hasStageSeparation: false,
      trajectoryWindowDeg: 25,
      timeWindowSec: 60,
    } as LaunchParams,
  },
  {
    id: 'NASA-M043',
    missionName: 'STS-125 (Atlantis)',
    programName: 'Space Shuttle Program',
    year: '2009',
    gameType: 'docking',
    difficulty: 5,
    briefing: "Last Hubble servicing — 5 consecutive spacewalks. Install Wide Field Camera 3, replace gyroscopes and batteries, and install the Cosmic Origins Spectrograph. Tools break. Work upside down. Get it done.",
    objective: 'Complete all 5 EVA tasks before the 11-day mission clock runs out.',
    funFact: "After STS-125, Hubble became the most productive science instrument in history. Its optics are expected to last until the 2030s.",
    params: {
      approachDistanceM: 400,
      maxApproachSpeedMs: 1,
      portDiameterPx: 50,
      thrusterStrength: 0.7,
      damping: 0.96,
      hasRollAxis: false,
      timeLimitSec: 130,
    } as DockingParams,
  },
  {
    id: 'NASA-M044',
    missionName: 'STS-135 (Atlantis)',
    programName: 'Space Shuttle Program',
    year: '2011',
    gameType: 'docking',
    difficulty: 3,
    briefing: "The final Space Shuttle flight — mission 135. Deliver the Raffaello logistics module packed with ISS supplies. Land at KSC for the last time. End of an era.",
    objective: 'Dock with ISS, transfer supplies using the robot arm, then perform a perfect runway landing.',
    funFact: "When Atlantis landed, shuttle workers wept on the runway. The Space Shuttle was retired after 30 years and 135 flights.",
    params: {
      approachDistanceM: 1000,
      maxApproachSpeedMs: 3,
      portDiameterPx: 70,
      thrusterStrength: 1.0,
      damping: 0.93,
      hasRollAxis: false,
      timeLimitSec: 100,
    } as DockingParams,
  },

  // ═══════════════════════════════
  // ISS & COMMERCIAL CREW (M045–M046)
  // ═══════════════════════════════
  {
    id: 'NASA-M045',
    missionName: 'ISS Expeditions (1 – Present)',
    programName: 'ISS Expeditions',
    year: '2000–Present',
    gameType: 'docking',
    difficulty: 3,
    briefing: "You are a crew member on ISS. Conduct science, perform an EVA maintenance spacewalk, and manage station attitude using the control moment gyroscopes.",
    objective: 'Complete the science experiment, perform an EVA bolt replacement, and fire thrusters to correct orbit decay.',
    funFact: 'ISS has been continuously inhabited since November 2, 2000 — more than 25 years. Over 270 people from 21 countries have visited.',
    params: {
      approachDistanceM: 200,
      maxApproachSpeedMs: 1,
      portDiameterPx: 85,
      thrusterStrength: 0.9,
      damping: 0.95,
      hasRollAxis: false,
      timeLimitSec: 100,
    } as DockingParams,
  },
  {
    id: 'NASA-M046',
    missionName: 'SpaceX Crew Dragon',
    programName: 'Commercial Crew',
    year: '2020–Present',
    gameType: 'docking',
    difficulty: 2,
    briefing: "Commercial crew era. Dragon docks autonomously — but you control the touchscreen backup. Approach ISS, match attitude, and soft-dock with the international docking adapter.",
    objective: 'Manually back-up Dragon\'s docking using the touchscreen to complete the approach.',
    funFact: "Demo-2 was the first American crewed launch from US soil since STS-135 in 2011 — after 9 years of riding Soyuz.",
    params: {
      approachDistanceM: 800,
      maxApproachSpeedMs: 2,
      portDiameterPx: 80,
      thrusterStrength: 1.0,
      damping: 0.95,
      hasRollAxis: false,
      timeLimitSec: 90,
    } as DockingParams,
  },

  // ═══════════════════════════════
  // ARTEMIS PROGRAM (M047–M049)
  // ═══════════════════════════════
  {
    id: 'NASA-M047',
    missionName: 'Artemis I',
    programName: 'Artemis Program',
    year: '2022',
    gameType: 'deep_space',
    difficulty: 3,
    briefing: "Uncrewed SLS/Orion test flight. Execute Trans-Lunar Injection, enter the Distant Retrograde Orbit 70,000 km beyond the Moon, then fire for high-speed reentry at 11 km/s.",
    objective: 'Navigate Orion through TLI, DRO insertion, and skip-entry reentry profile.',
    funFact: "Artemis I traveled 1.4 million km — farther from Earth than any capsule since Apollo 13. It tested the heat shield at 2760°C.",
    params: {
      numPlanets: 1,
      requiredSwingbys: 0,
      fuelBudget: 100,
      targetOrbitalRadius: 70000,
      gravityStrength: 1.62,
      timeLimitSec: 120,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M048',
    missionName: 'Artemis II',
    programName: 'Artemis Program',
    year: '2026',
    gameType: 'deep_space',
    difficulty: 3,
    briefing: "First crewed Artemis flight. 4 astronauts — 3 NASA, 1 CSA — fly a lunar free-return trajectory. Demonstrate proximity operations in LEO and verify deep-space life support.",
    objective: 'Execute LEO proximity maneuver, fly the lunar free-return arc, and verify all deep-space systems.',
    funFact: "Artemis II includes the first Canadian, the first woman, and the first person of color to fly a lunar trajectory.",
    params: {
      numPlanets: 1,
      requiredSwingbys: 0,
      fuelBudget: 100,
      targetOrbitalRadius: 3000,
      gravityStrength: 1.62,
      timeLimitSec: 120,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M049',
    missionName: 'Artemis III',
    programName: 'Artemis Program',
    year: '2027',
    gameType: 'lunar_landing',
    difficulty: 5,
    briefing: "The return to the Moon. Dock with the SpaceX Starship HLS in lunar orbit, then descend to the South Pole to collect water ice. The most complex lunar landing ever attempted.",
    objective: 'Descend to the lunar south pole, land within 50m of the ice deposit waypoint, and collect ice samples.',
    funFact: "The lunar south pole has permanently shadowed craters with water ice — left there by ancient comets — that could fuel future spacecraft.",
    params: {
      gravity: 1.62,
      fuelCapacity: 100,
      targetZoneWidthPx: 50,
      windDrift: 0,
      hasTerrainHazards: true,
      timeLimitSec: 130,
      altitudeStartM: 15000,
    } as LunarLandingParams,
  },

  // ═══════════════════════════════
  // ROBOTIC LUNAR (M050–M051)
  // ═══════════════════════════════
  {
    id: 'NASA-M050',
    missionName: 'Ranger & Surveyor Programs',
    programName: 'Robotic Lunar',
    year: '1961–1968',
    gameType: 'lunar_landing',
    difficulty: 2,
    briefing: "Surveyor — the first soft lunar lander. Descend using solid retro-rockets and vernier engines. Touch down gently enough for the legs to absorb the shock.",
    objective: 'Fire the Surveyor retro-rocket at the correct altitude and ease down on vernier engines.',
    funFact: "Ranger was designed to crash — it had no landing legs. It took thousands of photos on the way down before smashing into the Moon.",
    params: {
      gravity: 1.62,
      fuelCapacity: 100,
      targetZoneWidthPx: 130,
      windDrift: 0,
      hasTerrainHazards: false,
      timeLimitSec: 90,
      altitudeStartM: 4000,
    } as LunarLandingParams,
  },
  {
    id: 'NASA-M051',
    missionName: 'Lunar Reconnaissance Orbiter (LRO)',
    programName: 'Robotic Lunar',
    year: '2009–Present',
    gameType: 'telescope',
    difficulty: 2,
    briefing: "LRO maps the Moon at 50cm resolution — every boulder visible. Target the narrow-angle camera on polar craters to reveal water ice deposits and future landing sites.",
    objective: 'Lock the narrow-angle camera on 5 polar crater targets and complete imaging passes.',
    funFact: "LRO photographed the Apollo landing sites so clearly you can see the astronauts' footpaths in the lunar regolith.",
    params: {
      shimmerAmplitude: 0.2,
      targetSizePx: 25,
      numTargets: 5,
      lockTimeSec: 3,
      hasDrift: true,
      timeLimitSec: 90,
    } as TelescopeParams,
  },

  // ═══════════════════════════════
  // ROBOTIC MARS (M052–M057)
  // ═══════════════════════════════
  {
    id: 'NASA-M052',
    missionName: 'Mariner 4, 9',
    programName: 'Robotic Mars',
    year: '1964–1971',
    gameType: 'deep_space',
    difficulty: 2,
    briefing: "Mariner 4 — first successful Mars flyby. Thread the spacecraft past Mars close enough to take 21 photos with the TV camera, then telemeter the data back to Earth.",
    objective: 'Adjust trajectory for Mars flyby at 9,846 km, activate camera at closest approach, and telemeter data.',
    funFact: "Mariner 4's 21 photos were the first images from another planet. Scientists hand-colored a printout on the wall and stared at it for days.",
    params: {
      numPlanets: 1,
      requiredSwingbys: 0,
      fuelBudget: 100,
      targetOrbitalRadius: 9846,
      gravityStrength: 3.72,
      timeLimitSec: 110,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M053',
    missionName: 'Viking 1 & Viking 2',
    programName: 'Robotic Mars',
    year: '1975–1976',
    gameType: 'rover',
    difficulty: 3,
    briefing: "Viking — first successful Mars lander. After aeroshell, parachute, and retro-rocket touchdown, deploy the sampler arm to scoop Mars soil into the biology lab.",
    objective: 'Navigate the sampler arm to 4 soil sites and return samples to the biology experiment compartment.',
    funFact: "Viking's biology experiments gave ambiguous results — one experiment seemed positive for life, but the chemistry experiment was negative. The debate continues.",
    params: {
      gridCols: 10,
      gridRows: 10,
      craterDensity: 0.15,
      numWaypoints: 4,
      batteryCapacity: 100,
      sandstormProbability: 0.1,
      timeLimitSec: 100,
    } as RoverParams,
  },
  {
    id: 'NASA-M054',
    missionName: 'Mars Pathfinder & Sojourner',
    programName: 'Robotic Mars',
    year: '1996',
    gameType: 'rover',
    difficulty: 2,
    briefing: "Sojourner — the first Mars rover. A tiny 10kg robot. Drive off the lander ramps and analyze nearby rocks with the APXS spectrometer. Avoid sharp rocks that could puncture tires.",
    objective: 'Drive Sojourner to 4 rock targets and complete APXS analysis at each one.',
    funFact: "Sojourner was designed for a 7-day mission. It lasted 83 days. The team was devastated when it finally went silent.",
    params: {
      gridCols: 10,
      gridRows: 8,
      craterDensity: 0.2,
      numWaypoints: 4,
      batteryCapacity: 80,
      sandstormProbability: 0.05,
      timeLimitSec: 90,
    } as RoverParams,
  },
  {
    id: 'NASA-M055',
    missionName: 'MER Spirit & Opportunity',
    programName: 'Robotic Mars',
    year: '2003',
    gameType: 'rover',
    difficulty: 3,
    briefing: "Spirit and Opportunity — twin Mars Exploration Rovers. Navigate across Martian terrain to exposed rock outcrops. Use the Rock Abrasion Tool (RAT) to grind through the outer layer and expose fresh rock.",
    objective: 'Drive to 5 rock outcrops, use RAT grinding tool, and collect Mössbauer spectrometer readings.',
    funFact: "Opportunity was designed for 90 days and lasted 15 YEARS. It drove 45 km — a marathon. Its final transmission was cut off by a dust storm.",
    params: {
      gridCols: 14,
      gridRows: 12,
      craterDensity: 0.25,
      numWaypoints: 5,
      batteryCapacity: 90,
      sandstormProbability: 0.2,
      timeLimitSec: 120,
    } as RoverParams,
  },
  {
    id: 'NASA-M056',
    missionName: 'Curiosity Rover',
    programName: 'Robotic Mars',
    year: '2011–Present',
    gameType: 'rover',
    difficulty: 4,
    briefing: "Curiosity in Gale Crater. The Sky Crane lands you. Now navigate the crater floor toward Mount Sharp. Drill into rock beds, analyze with SAM mass spectrometer, manage the RTG power budget.",
    objective: 'Drive 8 waypoints across Gale Crater, drill 3 rock samples, and analyze with SAM.',
    funFact: "Curiosity drilled into rocks 3.5 billion years old and found organic molecules — the building blocks of life — preserved inside.",
    params: {
      gridCols: 16,
      gridRows: 14,
      craterDensity: 0.3,
      numWaypoints: 8,
      batteryCapacity: 100,
      sandstormProbability: 0.25,
      timeLimitSec: 140,
    } as RoverParams,
  },
  {
    id: 'NASA-M057',
    missionName: 'Perseverance & Ingenuity',
    programName: 'Robotic Mars',
    year: '2020–Present',
    gameType: 'rover',
    difficulty: 5,
    briefing: "Perseverance — the most advanced Mars rover. Seal rock cores in titanium tubes for future Mars Sample Return. Also, command Ingenuity helicopter for the first powered flight on another planet.",
    objective: 'Drive to 6 sample sites, seal cores, then navigate Ingenuity through 3 waypoint flights.',
    funFact: "Ingenuity's first flight on April 19, 2021 carried a postage-stamp piece of the Wright Brothers' original airplane — the first powered flight on another planet.",
    params: {
      gridCols: 18,
      gridRows: 16,
      craterDensity: 0.3,
      numWaypoints: 6,
      batteryCapacity: 100,
      sandstormProbability: 0.3,
      timeLimitSec: 150,
    } as RoverParams,
  },

  // ═══════════════════════════════
  // ROBOTIC VENUS & MERCURY (M058–M059)
  // ═══════════════════════════════
  {
    id: 'NASA-M058',
    missionName: 'Pioneer Venus & Magellan',
    programName: 'Robotic Venus',
    year: '1978–1989',
    gameType: 'deep_space',
    difficulty: 3,
    briefing: "Magellan uses Synthetic Aperture Radar to pierce Venus's 65km thick cloud deck and map 98% of the surface. Use aerobraking to lower the orbit — a first.",
    objective: 'Execute aerobraking passes to lower the orbit periapsis, then begin radar mapping swaths.',
    funFact: "Magellan found Venus has thousands more volcanoes than Earth. Some may still be active. The surface is hot enough to melt lead.",
    params: {
      numPlanets: 1,
      requiredSwingbys: 0,
      fuelBudget: 100,
      targetOrbitalRadius: 6052,
      gravityStrength: 8.87,
      timeLimitSec: 110,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M059',
    missionName: 'MESSENGER',
    programName: 'Robotic Mercury',
    year: '2004–2015',
    gameType: 'deep_space',
    difficulty: 4,
    briefing: "MESSENGER must slow down enough to orbit Mercury — one of the hardest navigation problems in the solar system. Execute 6 gravity assists (1 Earth, 2 Venus, 3 Mercury) across 7 years.",
    objective: 'Thread MESSENGER through the gravity assist sequence and achieve Mercury orbit insertion.',
    funFact: "Without the gravity assists, MESSENGER would have needed 5x more fuel than it could carry. The math took years to work out.",
    params: {
      numPlanets: 3,
      requiredSwingbys: 6,
      fuelBudget: 100,
      targetOrbitalRadius: 2440,
      gravityStrength: 3.7,
      timeLimitSec: 140,
    } as DeepSpaceParams,
  },

  // ═══════════════════════════════
  // OUTER PLANETS (M060–M065)
  // ═══════════════════════════════
  {
    id: 'NASA-M060',
    missionName: 'Pioneer 10 & 11',
    programName: 'Outer Planets',
    year: '1972–1973',
    gameType: 'deep_space',
    difficulty: 3,
    briefing: "Pioneer 10 — first spacecraft to cross the asteroid belt and reach Jupiter. Navigate through the asteroid belt and survive Jupiter's radiation belts while measuring the Jovian magnetic field.",
    objective: 'Navigate through the asteroid belt hazard zone, fly past Jupiter, and measure the radiation environment.',
    funFact: "Pioneer 10 crossed the orbit of Neptune in 1983 — first human-made object to do so. It carries a golden plaque showing where Earth is in the galaxy.",
    params: {
      numPlanets: 2,
      requiredSwingbys: 1,
      fuelBudget: 100,
      targetOrbitalRadius: 300000,
      gravityStrength: 24.79,
      timeLimitSec: 120,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M061',
    missionName: 'Voyager 1 & 2',
    programName: 'Outer Planets',
    year: '1977–Present',
    gameType: 'deep_space',
    difficulty: 4,
    briefing: "Voyager 2's Grand Tour — Jupiter, Saturn, Uranus, Neptune. Each planet acts as a gravitational slingshot. The alignment window that makes this possible occurs only once every 175 years.",
    objective: 'Execute 4 planetary gravity assists in sequence to complete the Grand Tour.',
    funFact: "Voyager 1 is now 24 billion km from Earth — the most distant human-made object. Its radio signal, traveling at light speed, takes 22 hours to reach us.",
    params: {
      numPlanets: 4,
      requiredSwingbys: 4,
      fuelBudget: 100,
      targetOrbitalRadius: 4000000,
      gravityStrength: 11.0,
      timeLimitSec: 150,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M062',
    missionName: 'Galileo',
    programName: 'Outer Planets',
    year: '1989–2003',
    gameType: 'deep_space',
    difficulty: 4,
    briefing: "Galileo releases its probe into Jupiter's atmosphere — 160 km of descent in 57 minutes. The high-gain antenna fails, so all science data must be compressed and stored on the tape recorder.",
    objective: 'Release the atmospheric probe at the right point, then relay its data back using the low-gain antenna workaround.',
    funFact: "Galileo's probe survived 22 times the pressure found at Earth's sea level before being crushed. It found that Jupiter's winds reach 600 km/h.",
    params: {
      numPlanets: 2,
      requiredSwingbys: 2,
      fuelBudget: 90,
      targetOrbitalRadius: 71492,
      gravityStrength: 24.79,
      timeLimitSec: 130,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M063',
    missionName: 'Cassini-Huygens',
    programName: 'Outer Planets',
    year: '1997–2017',
    gameType: 'deep_space',
    difficulty: 5,
    briefing: "13 years at Saturn. Release Huygens on Titan's atmosphere — the only probe to land on an outer-planet moon. Then dive through Enceladus geysers. Finally, 22 Grand Finale dives between Saturn and its rings.",
    objective: 'Release Huygens, execute Enceladus flyby through the plumes, then complete the Grand Finale ring-diving sequence.',
    funFact: "Huygens landed on Titan and sent back photos of a landscape of methane rivers and pebbles made of water ice. It survived 72 minutes before Cassini moved out of range.",
    params: {
      numPlanets: 3,
      requiredSwingbys: 4,
      fuelBudget: 100,
      targetOrbitalRadius: 60268,
      gravityStrength: 10.44,
      timeLimitSec: 150,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M064',
    missionName: 'New Horizons',
    programName: 'Outer Planets',
    year: '2006–Present',
    gameType: 'deep_space',
    difficulty: 3,
    briefing: "New Horizons wakes from 9 years of hibernation to fly past Pluto at 13,700 km/s. The encounter lasts only 30 minutes. Every instrument must fire automatically. No corrections possible.",
    objective: 'Wake the spacecraft from hibernation, execute the automated Pluto encounter sequence, and telemeter data.',
    funFact: "Pluto has a heart-shaped nitrogen ice plain the size of Texas — named Tombaugh Regio after Pluto's discoverer.",
    params: {
      numPlanets: 2,
      requiredSwingbys: 1,
      fuelBudget: 100,
      targetOrbitalRadius: 2377,
      gravityStrength: 0.62,
      timeLimitSec: 120,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M065',
    missionName: 'Juno & Europa Clipper',
    programName: 'Outer Planets',
    year: '2011–Present',
    gameType: 'telescope',
    difficulty: 4,
    briefing: "Europa Clipper scans the icy moon through 49 flybys. Ice-penetrating radar maps the subsurface ocean beneath Europa's frozen shell. Lock radar beams on the target region through 49 passes.",
    objective: 'Lock the ice-penetrating radar on Europa\'s subsurface ocean target zone for all 5 flyby passes.',
    funFact: "Europa's ocean contains more liquid water than all Earth's oceans combined — and it has been there for billions of years.",
    params: {
      shimmerAmplitude: 0.4,
      targetSizePx: 30,
      numTargets: 5,
      lockTimeSec: 4,
      hasDrift: true,
      timeLimitSec: 120,
    } as TelescopeParams,
  },

  // ═══════════════════════════════
  // ASTEROID EXPLORATION (M066–M069)
  // ═══════════════════════════════
  {
    id: 'NASA-M066',
    missionName: 'NEAR Shoemaker, Stardust, Deep Impact',
    programName: 'Asteroid Exploration',
    year: '1996–2005',
    gameType: 'deep_space',
    difficulty: 3,
    briefing: "Deep Impact fires a copper projectile at 10.2 km/s into Comet Tempel 1. The impact must hit within 100m of the target. Navigate the impactor in real-time.",
    objective: 'Guide the copper impactor to the target crater on Tempel 1 using autonomous navigation updates.',
    funFact: "The impact blasted a crater bigger than a football field and ejected 10,000 tons of ice and dust. Scientists were stunned by how much material came out.",
    params: {
      numPlanets: 1,
      requiredSwingbys: 0,
      fuelBudget: 100,
      targetOrbitalRadius: 3,
      gravityStrength: 0.0001,
      timeLimitSec: 90,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M067',
    missionName: 'Dawn',
    programName: 'Asteroid Exploration',
    year: '2007–2018',
    gameType: 'deep_space',
    difficulty: 3,
    briefing: "Dawn uses an ion engine — incredibly slow but incredibly efficient. Map Vesta, then use the ion drive for 2 years to spiral out to Ceres. First spacecraft to orbit two extraterrestrial bodies.",
    objective: 'Use the ion thruster to spiral out from Vesta orbit to Ceres orbit across the mission timeline.',
    funFact: "Dawn's ion engine generated only 91 millinewtons of thrust — less than the weight of a sheet of paper. Over 2 years, it changed the spacecraft's speed by 10 km/s.",
    params: {
      numPlanets: 2,
      requiredSwingbys: 0,
      fuelBudget: 100,
      targetOrbitalRadius: 940,
      gravityStrength: 0.28,
      timeLimitSec: 130,
    } as DeepSpaceParams,
  },
  {
    id: 'NASA-M068',
    missionName: 'OSIRIS-REx',
    programName: 'Asteroid Exploration',
    year: '2016–Present',
    gameType: 'docking',
    difficulty: 5,
    briefing: "OSIRIS-REx's Touch-And-Go (TAG) sample collection. Descend 20 meters to asteroid Bennu, touch the surface for 5 seconds, fire a nitrogen gas burst to collect rocks, then back away.",
    objective: 'Descend to Bennu\'s surface, touch for 5 seconds (TAG event), collect sample, and back away without tumbling.',
    funFact: "Bennu surprised the team by being covered in boulders instead of smooth regolith. The TAG arm collected 250g of material — more than the target of 60g.",
    params: {
      approachDistanceM: 20,
      maxApproachSpeedMs: 0.2,
      portDiameterPx: 25,
      thrusterStrength: 0.3,
      damping: 0.85,
      hasRollAxis: true,
      timeLimitSec: 120,
    } as DockingParams,
  },
  {
    id: 'NASA-M069',
    missionName: 'DART',
    programName: 'Asteroid Exploration',
    year: '2021–2022',
    gameType: 'deep_space',
    difficulty: 4,
    briefing: "Humanity's first planetary defense test. DART slams into Dimorphos at 6.6 km/s using SMART Nav autonomous guidance — no human in the loop. Lock onto the target and don't flinch.",
    objective: 'Lock SMART Nav onto Dimorphos and achieve hypervelocity impact within the target zone.',
    funFact: "DART shortened Dimorphos's orbital period by 33 minutes — 25x more than models predicted. The ejecta plume created a comet-like tail 10,000 km long.",
    params: {
      numPlanets: 1,
      requiredSwingbys: 0,
      fuelBudget: 100,
      targetOrbitalRadius: 160,
      gravityStrength: 0.00003,
      timeLimitSec: 90,
    } as DeepSpaceParams,
  },

  // ═══════════════════════════════
  // HELIOPHYSICS & OBSERVATORIES (M070–M074)
  // ═══════════════════════════════
  {
    id: 'NASA-M070',
    missionName: 'Parker Solar Probe',
    programName: 'Heliophysics',
    year: '1995–Present',
    gameType: 'telescope',
    difficulty: 4,
    briefing: "Parker Solar Probe flies closer to the Sun than any spacecraft — 6.1 million km. The carbon-composite heat shield blocks 99.97% of solar energy. Monitor the shield temperature and detect CME events.",
    objective: 'Track 5 coronal mass ejections across the solar disk before they impact the spacecraft heat shield.',
    funFact: "Parker Solar Probe moved at 692,000 km/h — the fastest human-made object ever. It literally 'touched' the Sun's corona.",
    params: {
      shimmerAmplitude: 0.7,
      targetSizePx: 20,
      numTargets: 5,
      lockTimeSec: 3,
      hasDrift: true,
      timeLimitSec: 100,
    } as TelescopeParams,
  },
  {
    id: 'NASA-M071',
    missionName: 'Hubble Space Telescope',
    programName: 'Great Observatories',
    year: '1990–Present',
    gameType: 'telescope',
    difficulty: 3,
    briefing: "Point Hubble's Fine Guidance Sensors to lock on a deep field target — a tiny patch of sky containing 10,000 galaxies. Hold lock to 0.007 arcseconds. The slightest vibration from the solar arrays ruins the exposure.",
    objective: 'Lock on 6 deep-field targets with Hubble\'s FGS and hold for a multi-hour exposure.',
    funFact: "The Hubble Deep Field image (a 10-day exposure of a tiny patch of sky) revealed 3,000 galaxies no one knew existed.",
    params: {
      shimmerAmplitude: 0.3,
      targetSizePx: 15,
      numTargets: 6,
      lockTimeSec: 5,
      hasDrift: true,
      timeLimitSec: 120,
    } as TelescopeParams,
  },
  {
    id: 'NASA-M072',
    missionName: 'Chandra & Spitzer',
    programName: 'Great Observatories',
    year: '1999–2020',
    gameType: 'telescope',
    difficulty: 3,
    briefing: "Chandra X-ray Observatory — images in X-rays, invisible to the human eye. Target black holes, supernova remnants, and galaxy clusters. X-ray sources move — track them through Chandra's elliptical orbit.",
    objective: 'Track 5 X-ray sources as Chandra sweeps through its orbit and lock for imaging.',
    funFact: "Chandra discovered that dark energy is real by measuring distant galaxy clusters. It proved Einstein's cosmological constant was not a mistake.",
    params: {
      shimmerAmplitude: 0.35,
      targetSizePx: 18,
      numTargets: 5,
      lockTimeSec: 4,
      hasDrift: true,
      timeLimitSec: 110,
    } as TelescopeParams,
  },
  {
    id: 'NASA-M073',
    missionName: 'Kepler & TESS',
    programName: 'Astrophysics',
    year: '2009–Present',
    gameType: 'telescope',
    difficulty: 2,
    briefing: "Kepler stares at 150,000 stars simultaneously. When a planet transits, the star dims by 0.01%. Detect the transit signal in the noisy photometry stream.",
    objective: 'Identify 8 planetary transit dip signatures in the star brightness data stream before the survey window closes.',
    funFact: "Kepler found 2,662 confirmed exoplanets — including 9 potentially Earth-sized planets in the habitable zone of their stars.",
    params: {
      shimmerAmplitude: 0.15,
      targetSizePx: 30,
      numTargets: 8,
      lockTimeSec: 2,
      hasDrift: false,
      timeLimitSec: 100,
    } as TelescopeParams,
  },
  {
    id: 'NASA-M074',
    missionName: 'James Webb Space Telescope',
    programName: 'Great Observatories',
    year: '2021–Present',
    gameType: 'telescope',
    difficulty: 5,
    briefing: "JWST's 18 hexagonal beryllium mirror segments must align to nanometer precision at 1.5 million km from Earth. Any misalignment blurs the entire universe-image. Align all 18 segments.",
    objective: 'Align all 18 mirror segment actuators to within 50nm tolerance before the cold telescope reaches operating temperature.',
    funFact: "JWST sees infrared light from galaxies 13.6 billion light-years away — formed just 300 million years after the Big Bang. Its first images made scientists cry.",
    params: {
      shimmerAmplitude: 0.1,
      targetSizePx: 10,
      numTargets: 8,
      lockTimeSec: 6,
      hasDrift: true,
      timeLimitSec: 140,
    } as TelescopeParams,
  },

  // ═══════════════════════════════
  // EARTH SCIENCE (M075–M076)
  // ═══════════════════════════════
  {
    id: 'NASA-M075',
    missionName: 'Landsat Program',
    programName: 'Earth Science',
    year: '1972–Present',
    gameType: 'telescope',
    difficulty: 1,
    briefing: "Landsat 9 orbits in a sun-synchronous polar orbit, imaging every patch of Earth every 16 days. Point the Operational Land Imager to track deforestation in the Amazon.",
    objective: 'Complete 4 imaging passes over the target region and classify land cover changes.',
    funFact: "Landsat's 50-year archive is the longest continuous record of Earth's surface changes. It revealed the shrinking of the Aral Sea, Amazon deforestation, and glacial retreat.",
    params: {
      shimmerAmplitude: 0.25,
      targetSizePx: 45,
      numTargets: 4,
      lockTimeSec: 2,
      hasDrift: false,
      timeLimitSec: 80,
    } as TelescopeParams,
  },
  {
    id: 'NASA-M076',
    missionName: 'Terra, Aqua, Aura & NISAR',
    programName: 'Earth Science',
    year: '1999–Present',
    gameType: 'telescope',
    difficulty: 2,
    briefing: "NISAR — NASA-ISRO joint mission. Dual-frequency SAR radar maps Earth surface deformation to 1cm accuracy. Detect tectonic stress buildup before an earthquake.",
    objective: 'Lock NISAR\'s dual SAR beams on 5 fault zones and detect deformation signatures.',
    funFact: "NISAR will map all of Earth's land and ice every 12 days — detecting centimeter-scale ground movement across fault zones, volcanoes, and ice sheets.",
    params: {
      shimmerAmplitude: 0.2,
      targetSizePx: 35,
      numTargets: 5,
      lockTimeSec: 3,
      hasDrift: false,
      timeLimitSec: 90,
    } as TelescopeParams,
  },
];

// ──────────────────────────────────────────────
// Helper utilities
// ──────────────────────────────────────────────

export function getMissionById(id: string): MissionGameConfig | undefined {
  return MISSION_GAME_DATA.find((m) => m.id === id);
}

export function getMissionsByProgram(programName: string): MissionGameConfig[] {
  return MISSION_GAME_DATA.filter((m) => m.programName === programName);
}

export function getMissionsByGameType(gameType: GameType): MissionGameConfig[] {
  return MISSION_GAME_DATA.filter((m) => m.gameType === gameType);
}

export const PROGRAM_ORDER = [
  'Project Mercury',
  'Project Gemini',
  'Apollo Program',
  'Skylab Program',
  'Apollo-Soyuz',
  'Space Shuttle Program',
  'ISS Expeditions',
  'Commercial Crew',
  'Artemis Program',
  'Robotic Lunar',
  'Robotic Mars',
  'Robotic Venus',
  'Robotic Mercury',
  'Outer Planets',
  'Asteroid Exploration',
  'Heliophysics',
  'Great Observatories',
  'Astrophysics',
  'Earth Science',
];

export const GAME_TYPE_LABELS: Record<GameType, string> = {
  launch: '🚀 Launch & Ascent',
  docking: '🛸 Orbital Docking',
  lunar_landing: '🌑 Lunar Landing',
  rover: '🤖 Rover Navigation',
  telescope: '🔭 Telescope Ops',
  deep_space: '☄️ Deep Space Nav',
};

export const GAME_TYPE_COLORS: Record<GameType, string> = {
  launch: '#f97316',
  docking: '#06b6d4',
  lunar_landing: '#8b5cf6',
  rover: '#22c55e',
  telescope: '#eab308',
  deep_space: '#ec4899',
};
